### ISSUE TITLE
CNV calling 

### ISSUE THREAD

**Issue by woodyNsinbad** [gatk-workflows/gatk4-somatic-cnvs#4]
is the latest wdl file for somatic CNV test work ? I try to run it with my own interval but it seems I should use same interval file for tumor and normal but in the wdl ,it would use **preprocessinterval** to preprocess the interval file for tumor ,what I can do to elude this problem ？

**Comment by bshifaw** [comment]
Hi, 
Please post questions to the [GATK forum](https://gatkforums.broadinstitute.org/gatk/).
Also please include error messages you received and the reference/resource files being used in your test.

**Comment by fleharty** [comment]
@bshifaw Can this issue be closed?
